// export { default as  } from '';
export { default as Homepage } from './homepage';
export { default as Secondpage } from './secondpage';
export { default as NotFound } from './notfound';
export { default as Support } from './Support/Support';
export { default as Contact } from './Contact/Contact';
export { default as SignIn } from './SignIn/SignIn';
export { default as Createpage } from './Admin/Createpage';
export { default as Editor } from './Admin/Editor';
export { default as Chandler_Page} from './chandler_page/chandler_page';
export { default as Shane_Page} from './shane_page/shanepage';
export { default as Ryan_Page} from './ryan_page/ryan_page';