// export { default as  } from '';
export { default as Homepage } from './homepage';
export { default as Secondpage } from './secondpage';
export { default as NotFound } from './notfound';
export { default as Support } from './Support/Support';
export { default as Contact } from './Contact/Contact';
export { default as SignIn } from './SignIn/SignIn';
export { default as Createpage } from './Admin/Createpage';
export { default as Editor } from './Admin/Editor';